# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检查更新
      uses: actions/checkout@v2
    - name: 设置 node 环境
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: 安装项目
      run: |
        npm c
        npm run build
    - name: 发布
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      uses: ridedott/release-me-action@v2.2.64
      with:
        release-assets: |
          ./lib
          package.json
       
   
